### ISSUE TITLE
Minify

### ISSUE THREAD

**Issue by Bluxart** [askupasoftware/wp-dynamic-css#5]
Great library for my projects, I test today. Otherwise it is possible add in near future insert an option to  minify the external css output?

**Comment by ykadosh** [comment]
That's a great idea! I'll add it to the plugin's road map / todo list. The only issue I can think of is how can we handle multiple stylesheet callbacks - do we minify all of them, or do we minify on a per-style basis?
I tend to go with the 2nd option since this library might be used by multiple plugins at the same time, and so this option should be available to turn on/off for each stylesheet.

**Comment by ykadosh** [comment]
Added in version 1.0.4
